version: "3.5"
services:
  app:
    build:
      context: ./
    networks:
      - nginx-proxy
    restart: always
    ports:
      - 3000:3000
    environment:
      HTTPS_METHOD: "noredirect"
      VIRTUAL_HOST: "tronode.getid.org"
      LETSENCRYPT_HOST: "tronode.getid.org"

networks:
  nginx-proxy:
    external: true
